services:
  backend:
    build:
      context: ../.
      dockerfile: ./backend/Dockerfile 
      target: development
    restart: unless-stopped
    env_file: ".env"
    ports:
      - ${API_PORT}:3000
    volumes:
      - /app/node_modules
      - ../backend/src:/app/backend/src:rw
      - ../shared:/app/shared:rw

  frontend:
    build:
      context: ../.
      dockerfile: ./frontend/Dockerfile 
      target: development
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - /app/node_modules
      - ../frontend/src:/app/frontend/src:rw
      - ../shared:/app/shared:rw
      - ../backend:/app/backend:rw
    ports:
      - "${DASHBOARD_FRONTEND_PORT}:9000"
    depends_on:
      - backend
