services:
  backend:
    build:
      context: ../.
      dockerfile: ./backend/Dockerfile 
      target: development
    restart: unless-stopped
    env_file: ".env"
    ports:
      - ${API_PORT}:3000
    volumes:
      - /app/node_modules
      - ../backend/src:/app/backend/src:rw
      - ../shared:/app/shared:rw
      # Раскомментируйте если нужно будет на этапе разработки
      # - ${LOGS_FOLDER_PATH}:/logs:rw
      # - ${DOCS_FOLDER_PATH}:/journals:rw
    depends_on:
      - postgres

  frontend:
    build:
      context: ../.
      dockerfile: ./frontend/Dockerfile 
      target: development
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - /app/node_modules
      - ../frontend/src:/app/frontend/src:rw
      - ../shared:/app/shared:rw
      - ../backend:/app/backend:rw
    ports:
      - "${DASHBOARD_FRONTEND_PORT}:9000"
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST_AUTH_METHOD: trust  
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ~/service_volumes/sample_dev/postgres:/var/lib/postgresql/data